//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoMy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Header
    {
        public int ProductHeaderId { get; set; }
        public int CategoryId { get; set; }
        public int BannerId { get; set; }
        public int StockStatusId { get; set; }
        public int LocationId { get; set; }
        public int ProductTypeId { get; set; }
        public int UserId { get; set; }
        public string Sku { get; set; }
        public string Upc { get; set; }
        public string Model { get; set; }
        public string Class { get; set; }
        public string Engine { get; set; }
        public string CompressionRatio { get; set; }
        public string MaxTorque { get; set; }
        public string Transmision { get; set; }
        public string FrontTyre { get; set; }
        public string OverallLength { get; set; }
        public string OverallHeight { get; set; }
        public string SeatHeight { get; set; }
        public string FuelCapacity { get; set; }
        public string HorsePower { get; set; }
        public string YearUsed { get; set; }
        public string PlateNo { get; set; }
        public string Qty { get; set; }
        public string Price { get; set; }
        public bool ModFeatured { get; set; }
        public Nullable<int> CreationDate { get; set; }
        public Nullable<short> CreationTime { get; set; }
        public string CreationUser { get; set; }
        public Nullable<int> ModifyDate { get; set; }
        public Nullable<short> ModifyTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<int> DeleteDate { get; set; }
        public Nullable<short> DeleteTime { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<short> RecordStatus { get; set; }
    }
}
