//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoMy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public int UserRoleId { get; set; }
        public Nullable<int> BlobId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string IcNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool ModSubscribe { get; set; }
        public Nullable<int> CreationDate { get; set; }
        public Nullable<short> CreationTime { get; set; }
        public string CreationUser { get; set; }
        public Nullable<int> ModifyDate { get; set; }
        public Nullable<short> ModifyTime { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<int> DeleteDate { get; set; }
        public Nullable<short> DeleteTime { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<short> RecordStatus { get; set; }
    }
}
